name: Build and Release wtime.exe

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from VERSION file
        id: vars
        shell: pwsh
        run: |
          $version = Get-Content VERSION
          "version=$version" >> $env:GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller colorama

      - name: Build wtime_py.exe with PyInstaller
        shell: cmd
        run: |
          pyinstaller ^
            --noconfirm ^
            --onefile ^
            --console ^
            --icon "assets/clock.ico" ^
            --clean ^
            --optimize 2 ^
            --name wtime_py ^
            src/wtime.py

      - name: Build wtime_cpp.exe with MSVC
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ^
            -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^
            -property installationPath > temp_path.txt

          set /p VC_PATH=<temp_path.txt
          call "%VC_PATH%\VC\Auxiliary\Build\vcvars64.bat" && ^
          cl /O2 /std:c++20 /Zc:__cplusplus /D_HAS_CXX20_FORMAT=1 /Fe:wtime_cpp.exe src\wtime.cpp

      - name: Create GitHub Release and upload EXEs
        uses: softprops/action-gh-release@v2
        with:
          name: "wtime v${{ steps.vars.outputs.version }}"
          tag_name: "v${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false
          files: |
            dist/wtime_py.exe
            wtime_cpp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
